name: CVEScan CI

on: [push, pull_request]

jobs:
  test:
    name: ubuntu / ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install latest pip, setuptools, wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel virtualenv --upgrade-strategy=eager
    - name: Run tests
      env:
        CI: '1'
      run: |
        virtualenv .venv --system-site-packages && \
          source .venv/bin/activate && \
          python -m pip install pytest-cov -e . --upgrade --upgrade-strategy=eager && \
          python -m pytest -ra tests/

